# Ex3 - Getting and Knowing your Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [5]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [18]:
users = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user',sep='|')
users.set_index('user_id', inplace=True)
users

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
...      ...    ...            ...      ...
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

[943 rows x 4 columns]

### Step 4. See the first 25 entries

In [24]:
users[:25]

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

### Step 5. See the last 10 entries

In [9]:
users[-10:]

     user_id  age gender     occupation zip_code
933      934   61      M       engineer    22902
934      935   42      M         doctor    66221
935      936   24      M          other    32789
936      937   48      M       educator    98072
937      938   38      F     technician    55038
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

### Step 6. What is the number of observations in the dataset?

In [ ]:
num_observations = users.shape[0]
num_observations

### Step 7. What is the number of columns in the dataset?

In [20]:
num_columns = users.shape[1] # shape[0]은 행 개수, shape[1]은 열 개수
print("Number of columns:", num_columns)

Number of columns: 4

### Step 8. Print the name of all the columns.

In [26]:
print(users.columns)

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

### Step 9. How is the dataset indexed?

In [19]:
# 데이터셋의 인덱스 확인
print(users.index)

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
      dtype='int64', name='user_id', length=943)

### Step 10. What is the data type of each column?

In [ ]:
users_dtypes = users.dtypes
users_dtypes

### Step 11. Print only the occupation column

In [ ]:
print(users["occupation"])

### Step 12. How many different occupations are in this dataset?

In [28]:
users['occupation'].nunique()

21

### Step 13. What is the most frequent occupation?

In [13]:
users['occupation'].value_counts(ascending=False).head(1)

occupation
student    196
Name: count, dtype: int64

### Step 14. Summarize the DataFrame.

In [23]:
users_summary = users.describe(include="all")
users_summary

               age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

### Step 15. Summarize all the columns

In [22]:
summary = users.describe(include="all") # user.describe()는 기본적으로 숫자형 컬럼만 요약, index="all" 추가하면 문자형컬럼까지 요약
print(summary)

               age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

### Step 16. Summarize only the occupation column

In [25]:
users['occupation'].describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

### Step 17. What is the mean age of users?

(round to a whole number(make it integer))

In [16]:
mean_age = users['age'].mean()
round(mean_age)

34

### Step 18. What is the age with least occurrence?

In [21]:
users_least_occurrence=users['age'].value_counts().idxmin()
users_least_occurrence

7